functions:
  "fetch source":
  - command: git.get_project
    params: {directory: libmongocrypt}

  "make files executable":
  - command: shell.exec
    params:
      working_dir: libmongocrypt
      script: |-
        set -o errexit
        for i in $(find .evergreen -name \*.sh); do
          chmod +x $i
        done

pre:
- func: "fetch source"
- func: "make files executable"
- command: shell.exec
  params:
    working_dir: libmongocrypt
    script: ./.evergreen/pre.sh

tasks:
# Compile tasks take the form:
# compile-{debug|release}-ssl:{openssl|mac|windows}
- name: compile-debug-ssl:openssl
  commands:
  - command: shell.exec
    params:
      script: ./.evergreen/compile.sh

buildvariants:
- name: ubuntu1604
  display_name: "Ubuntu 16.04"
  run_on: localhostdistro
  tasks:
  - compile-debug-ssl:openssl
