functions:
  "fetch source":
  - command: git.get_project
    params: {directory: libmongocrypt}

pre:
- func: "fetch source"
- command: shell.exec
  working_dir: libmongocrypt
  params: { script: "sh ./.evergreen/pre.sh" }

tasks:
- name: compile-openssl
  commands:
  - command: shell.exec
    params:
      script: |-
        echo "Compile placeholder"

buildvariants:
- name: ubuntu1604
  display_name: "Ubuntu 16.04"
  run_on: ubuntu1604-test
  tasks:
  - compile-openssl
