functions:
  "fetch source":
  - command: git.get_project
    params: {directory: libmongocrypt}

  "make files executable":
  - command: shell.exec
    params:
      working_dir: libmongocrypt
      script: |-
        set -o errexit
        for i in $(find .evergreen -name \*.sh); do
          chmod +x $i
        done

pre:
- func: "fetch source"
- func: "make files executable"
- command: shell.exec
  working_dir: libmongocrypt
  params: { script: "sh ./.evergreen/pre.sh" }

tasks:
- name: compile-openssl
  commands:
  - command: shell.exec
    params:
      script: |-
        echo "Compile placeholder"

buildvariants:
- name: ubuntu1604
  display_name: "Ubuntu 16.04"
  run_on: ubuntu1604-test
  tasks:
  - compile-openssl
